In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans

from sklearn.metrics.pairwise import cosine_similarity

# 문제에 대한 정보
problem = pd.read_csv('tag_key.csv')

In [87]:
user = pd.read_csv('userSolved.csv')

In [88]:
problem.shape

(5598, 195)

In [89]:
# 사용할 Column
# problemid, level, averageTries, tag-key
# 데이터 전처리
problem = problem.iloc[:,1:]
problem.head()

problemId  level  math  implementation  dp  graphs  data_structures  \
0       1000      1     1               1   0       0                0   
1       1001      1     1               1   0       0                0   
2       1271      1     1               0   0       0                0   
3       1550      1     1               1   0       0                0   
4       2338      1     1               0   0       0                0   

   string  greedy  bruteforcing  ...  top_tree  chordal_graph  majority_vote  \
0       0       0             0  ...         0              0              0   
1       0       0             0  ...         0              0              0   
2       0       0             0  ...         0              0              0   
3       0       0             0  ...         0              0              0   
4       0       0             0  ...         0              0              0   

   a_star  rb_tree  birthday  degree_sequence  discrete_kth_root  \
0       0        0         0                0                  0   
1       0        0         0                0                  0   
2       0        0         0                0                  0   
3       0        0         0                0                  0   
4       0        0         0                0                  0   

   multipoint_evaluation  differential_cryptanalysis  
0                      0                           0  
1                      0                           0  
2                      0                           0  
3                      0                           0  
4                      0                           0  

[5 rows x 194 columns]

In [90]:
user.head()

userId  solved
0  koosaga    1000
1  koosaga    1001
2  koosaga    1002
3  koosaga    1003
4  koosaga    1004

In [91]:
user.columns = ['userId', 'problemId']

In [92]:
user.head()

userId  problemId
0  koosaga       1000
1  koosaga       1001
2  koosaga       1002
3  koosaga       1003
4  koosaga       1004

In [93]:
# 데이터 중복행 삭제
problem = problem.drop_duplicates()
problem.head()
problem_no = problem.iloc[:,1:]

In [94]:
k = 30
model = KMeans(n_clusters=k, random_state=10)
model.fit(problem_no)

KMeans(n_clusters=30, random_state=10)

In [95]:
problem['cluster'] = model.fit_predict(problem_no)

In [96]:
problem.tail()

problemId  level  math  implementation  dp  graphs  data_structures  \
5593      21837     10     0               0   0       1                1   
5594      21855     10     0               0   0       0                0   
5595      21917     10     0               0   0       1                0   
5596      21937     10     0               0   0       1                0   
5597      21959     10     1               0   0       0                0   

      string  greedy  bruteforcing  ...  chordal_graph  majority_vote  a_star  \
5593       1       0             0  ...              0              0       0   
5594       0       0             0  ...              0              0       0   
5595       0       1             0  ...              0              0       0   
5596       0       0             0  ...              0              0       0   
5597       0       0             0  ...              0              0       0   

      rb_tree  birthday  degree_sequence  discrete_kth_root  \
5593        0         0                0                  0   
5594        0         0                0                  0   
5595        0         0                0                  0   
5596        0         0                0                  0   
5597        0         0                0                  0   

      multipoint_evaluation  differential_cryptanalysis  cluster  
5593                      0                           0       20  
5594                      0                           0        5  
5595                      0                           0        5  
5596                      0                           0       20  
5597                      0                           0       26  

[5 rows x 195 columns]

In [97]:
problem['cluster']

0       24
1       24
2       24
3        3
4       24
        ..
5593    20
5594     5
5595     5
5596    20
5597    26
Name: cluster, Length: 4870, dtype: int32

In [98]:
user_problem = pd.merge(user, problem, on="problemId")

In [99]:
user_problem.head()

userId  problemId  level  math  implementation  dp  graphs  \
0              koosaga       1000      1     1               1   0       0   
1             cki86201       1000      1     1               1   0       0   
2  mitnegativeinfinity       1000      1     1               1   0       0   
3                ainta       1000      1     1               1   0       0   
4               yclock       1000      1     1               1   0       0   

   data_structures  string  greedy  ...  chordal_graph  majority_vote  a_star  \
0                0       0       0  ...              0              0       0   
1                0       0       0  ...              0              0       0   
2                0       0       0  ...              0              0       0   
3                0       0       0  ...              0              0       0   
4                0       0       0  ...              0              0       0   

   rb_tree  birthday  degree_sequence  discrete_kth_root  \
0        0         0                0                  0   
1        0         0                0                  0   
2        0         0                0                  0   
3        0         0                0                  0   
4        0         0                0                  0   

   multipoint_evaluation  differential_cryptanalysis  cluster  
0                      0                           0       24  
1                      0                           0       24  
2                      0                           0       24  
3                      0                           0       24  
4                      0                           0       24  

[5 rows x 196 columns]

In [100]:
user_problem_pi = user_problem.pivot_table('cluster', index='problemId', columns='userId')

In [101]:
user_problem_pi.head()

userId     0000000000  0000064  0000sb  0004poppop  000ian   001  001dltmdals  \
problemId                                                                       
1000             24.0     24.0    24.0        24.0     NaN  24.0          NaN   
1001             24.0     24.0    24.0        24.0     NaN  24.0          NaN   
1002             12.0      NaN     NaN         NaN     NaN  12.0          NaN   
1003             27.0      NaN     NaN         NaN     NaN  27.0          NaN   
1004              NaN      NaN     NaN         NaN     NaN  27.0          NaN   

userId     0021  006ws  007001as  ...  zzzwldy  zzzxc123  zzzz01111  zzzz465  \
problemId                         ...                                          
1000       24.0   24.0      24.0  ...     24.0      24.0       24.0     24.0   
1001        NaN   24.0       NaN  ...     24.0      24.0       24.0     24.0   
1002       12.0    NaN       NaN  ...     12.0       NaN        NaN     12.0   
1003       27.0   27.0       NaN  ...     27.0       NaN        NaN     27.0   
1004       27.0   27.0       NaN  ...     27.0       NaN        NaN      NaN   

userId     zzzzddz  zzzzll  zzzzong123  zzzzz9887  zzzzzzzz  zzzzzzzzu2  
problemId                                                                
1000           NaN    24.0        24.0       24.0      24.0        24.0  
1001           NaN    24.0         NaN       24.0      24.0        24.0  
1002           NaN    12.0         NaN        NaN      12.0         NaN  
1003           NaN    27.0         NaN        NaN       NaN         NaN  
1004           NaN    27.0         NaN        NaN       NaN         NaN  

[5 rows x 63758 columns]

In [102]:
user_problem_pi.fillna(31,inplace=True)
user_problem_pi.head()

userId     0000000000  0000064  0000sb  0004poppop  000ian   001  001dltmdals  \
problemId                                                                       
1000             24.0     24.0    24.0        24.0    31.0  24.0         31.0   
1001             24.0     24.0    24.0        24.0    31.0  24.0         31.0   
1002             12.0     31.0    31.0        31.0    31.0  12.0         31.0   
1003             27.0     31.0    31.0        31.0    31.0  27.0         31.0   
1004             31.0     31.0    31.0        31.0    31.0  27.0         31.0   

userId     0021  006ws  007001as  ...  zzzwldy  zzzxc123  zzzz01111  zzzz465  \
problemId                         ...                                          
1000       24.0   24.0      24.0  ...     24.0      24.0       24.0     24.0   
1001       31.0   24.0      31.0  ...     24.0      24.0       24.0     24.0   
1002       12.0   31.0      31.0  ...     12.0      31.0       31.0     12.0   
1003       27.0   27.0      31.0  ...     27.0      31.0       31.0     27.0   
1004       27.0   27.0      31.0  ...     27.0      31.0       31.0     31.0   

userId     zzzzddz  zzzzll  zzzzong123  zzzzz9887  zzzzzzzz  zzzzzzzzu2  
problemId                                                                
1000          31.0    24.0        24.0       24.0      24.0        24.0  
1001          31.0    24.0        31.0       24.0      24.0        24.0  
1002          31.0    12.0        31.0       31.0      12.0        31.0  
1003          31.0    27.0        31.0       31.0      31.0        31.0  
1004          31.0    27.0        31.0       31.0      31.0        31.0  

[5 rows x 63758 columns]

In [103]:
problem_sim = cosine_similarity(user_problem_pi,user_problem_pi).argsort()[:,::-1]

In [104]:
print(problem_sim)

[[   0    1    5 ...  424 2084  421]
 [   1    0 2179 ... 2084  424  421]
 [   2  616  596 ...  424 2084  421]
 ...
 [4867 4761 1645 ...  424 2084  421]
 [4868 1707 2884 ...  424 2084  421]
 [4869 4868 1883 ...  424 2084  421]]


In [110]:
def get_recommand_problem(df, problemId, top=30):
    target_problem_index = df[df['problemId'] == problemId].index.values
    
    # 코사인 유사도중 비슷한 코사인 유사도를 가진 정보를 뽑아낸다.
    sim_index = problem_sim[target_problem_index, :top].reshape(-1)
    # 본인 제외
    sim_index = sim_index[sim_index != target_problem_index]
    
    result = df.iloc[sim_index].sort_values('level', ascending=True)[:3]
    return result

In [113]:
get_recommand_problem(problem,14491)

problemId  level  math  implementation  dp  graphs  data_structures  \
175      21598      2     0               1   0       0                0   
651      24830      3     1               1   0       0                0   
311       6436      3     1               1   0       0                0   

     string  greedy  bruteforcing  ...  chordal_graph  majority_vote  a_star  \
175       0       0             0  ...              0              0       0   
651       0       0             0  ...              0              0       0   
311       0       0             0  ...              0              0       0   

     rb_tree  birthday  degree_sequence  discrete_kth_root  \
175        0         0                0                  0   
651        0         0                0                  0   
311        0         0                0                  0   

     multipoint_evaluation  differential_cryptanalysis  cluster  
175                      0                           0        3  
651                      0                           0        8  
311                      0                           0        8  

[3 rows x 195 columns]